return {
  { "tpope/vim-commentary" },
  { "tpope/vim-unimpaired" },
  { "tpope/vim-fugitive" },
  { "tpope/vim-ragtag" },
  { "junegunn/gv.vim" },
  { "tpope/vim-rails" },
  { "tpope/vim-rhubarb" },
  { "tpope/vim-surround" },
  { "tpope/vim-projectionist" },
  { "vim-ruby/vim-ruby" },
  { "yegappan/mru" },
  { "p00f/alabaster.nvim" },
  { "tek/vim-textobj-ruby", dependencies = { "kana/vim-textobj-user" } },
}
